---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# dsopts

<!-- badges: start -->
<!-- badges: end -->

The goal of dsopts is to provide the set of options used in datasketch data visualization and processing packages

## Installation

You can install the development version of dsopts from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("datasketch/dsopts")
```

## Examples 

To see all available options use: `dsopts_available()`


```{r}
library(dsopts)
## basic example code

# See all available options for a category
dsopts_available("treemap")

# See all available options for a category
dsopts_available("zoom")

# Can handle multiple categories

# This returns the options with both categories
dsopts_available(c("map", "bubble"))

# This returns the options with any of categories
dsopts_available(c("map", "bubble"), type = "any_of")


```


To get defaults

```{r}

dsopts_default(categories = "donut")

```



To override defaults

```{r}

  dsopts_merge(donut_width = 1, categories = "donut")

```
To override defaults with a list of options

```{r}

  opts <- list(
    donut_width = 2
  )
  dsopts_merge(donut_width = 1, opts = opts, categories = "donut")

```


