---
title: "dataprep options"
output: html_document
---

This document aims to explain the options available in the dataprep category. It will discuss the purpose of each argument, the possible values it can take, and the expected outcome of each argument.

* ####  agg 
The `agg` argument (which refers to aggregation) determines how data is summarized or combined, such as sums, averages, maximums, minimums, etc. It expects a value of type `character` and must be specified with the names of the corresponding functions (mean, max, min, etc.). By default, its value is "sum." Additionally, its hd_type is Categorical (Cat) and can take the following values: "sum Cat," "mean Cat," "max Cat," "min Cat," "std Cat," or "growth Cat."
  
* #### agg_na_rm 
The `agg_na_rm` argument indicates whether missing values (NA) should be removed before aggregating data. It expects a value of type logical, which represents boolean values (with possible values being True or False). By default, its value is TRUE, and its hd_type is Check (Chk).

* #### agg_text 
The `agg_text` argument is used as a label in the column name where a specific aggregation is performed. This argument is also located in the "text" category. Its default value is NULL, and its hd_type is Txt (Text). Some of the possible values it can take are: 'sum VAR,' 'mean VAR,' 'max VAR.' This argument should be used to specify the type of aggregation performed on the data in the column. For example, it can be used to indicate that the data has been summed, averaged, or that the maximum value has been taken.

* #### drop_na 
The `drop_na` argument serves to exclude missing data (NA) from a visualization if set to TRUE. Its purpose is to enhance the clarity of the visual representation by removing any missing values and its hdtype is Chk (Check).This expects a logical value (TRUE or FALSE) and by default, its value is FALSE.
  
* #### drop_na_var2 
  The `drop_na_var2` argument removes missing data (NA) from a second variable in the visualization. Its default value is FALSE, its `hdtype` is Chk (Check), and its possible values are TRUE or FALSE.
  
* #### format_number_prefix 
The format_number_prefix argument formats numeric values using SI prefixes to represent large numbers in a more readable format such as k (thousands), M (millions) in numeric values.This argument expects a logical value (TRUE or FALSE), its default value is FALSE and its hdtype is chk (Check). If is TRUE enables the formatting feature, while if is FALSE retains the original numeric values without SI prefixes.

* #### format_sample_cat 
  The `format_sample_cat`argument allows specifying how categorical data should be formatted, such as whether to convert them to uppercase, lowercase, etc. Its `hdtype` is Txt (text) and it is found in the theme, format, and dataclean categories. Its default value is NULL, which means no default formatting is applied.


* #### format_sample_dat 
 The `format_sample_dat` argument is used to format date-type data and allows to specify how date-type data should be formatted (for example YYYY-MM-DD or DD/MM/YYYY). It is also found in the theme and format categories, and its hdtype is Txt (text). The default value is NULL, indicating that no specific formatting is applied by default. 

* #### format_sample_num 
 The `format_sample_num` argument is used to set the format for numbers in the visualization. If no format is specified for axes, all numbers will use the format specified by this argument. The default value is 1500(Review) and is also found in the theme and format categories. This argument expects a `character` type (Review).

* #### na_label 
The `na_label` argument serves to provide a way to label NA values with a specific text string, improving the readability and understanding of the data. For example, if a dataset contains NA values in a column representing "Income," using `na_label = "Not Available"` would display "Not Available" instead of NA in the visual representation of the data. It is also found in the text category and its `hdtype` is Txt (text). This argument expects a `character` type value and can take any text string to be used as a replacement label for NA values.

* #### percentage 
The `percentage` argument, when set to TRUE, calculates the percentage for the indicated numerical variable. It is also found in the bar and pie categories. Its default value is FALSE, and its `hdtype` is chk (check). This argument expects a logical value (TRUE or FALSE) and is used to determine whether percentages should be calculated and displayed alongside the numerical variable in the visualization.

* #### percentage_col 
The `percentage_col` argument specifies the name or names of the categorical variable(s) for which you want to calculate percentages.For example, if you have a dataset with columns "category" and "value" representing different categories and their corresponding values, you can use percentage_col = "category" to calculate the percentage of each category. Its default value is NULL, and its `hdtype` is Txt (text). 

* #### percentage_intra 
  The `percentage_intra` argument calculates percentages within individual categories or groups in a visualization. Its default value is FALSE, and its `hdtype` is Chk (Check). This argument expects a logical value (TRUE or FALSE) and is used to determine whether percentages should be calculated within each category or group.

* #### percentage_name 
The `percentage_name` argument specifies a character value that will be used as the name for the column containing the calculated percentages. It is used to provide a more descriptive name for the percentage column in the output visualization or dataset  if `percentage` is TRUE. Its `hdtype` is Txt (text) and the type of the input is character (text).

* #### tooltip_agg_collapse_rows_template
The `tooltip_agg_collapse_rows_template` argument controls the aggregation of data in tooltips, determining whether similar or related rows are collapsed into a single entry in the tooltip to avoid repetition. It takes a dataframe and a template as inputs and returns a column of strings with the applied template. The template can apply different aggregations such as mean or max. This argument is found in the tooltip category, and its `hdtype` is Cat (categorical). Its possible values are functions such as sum, mean, etc., which are used to specify the type of aggregation to be applied in the tooltip.
  
* #### tooltip_include_all_vars 
The `tooltip_include_all_vars` argument includes all available variables in the entered dataframe for visualization. It is also found in the tooltip category, with a default value of FALSE. Its `hdtype` is Chk (Check).

* #### tooltip_sep_all_vars 
The `tooltip_sep_all_vars` argument specifies the separator used in tooltips when multiple variables are included, allowing for clear separation and organization of information.. It is also found in the tooltip category, and its `hdtype` is Cat (categorical).

* #### tooltip_template 
The tooltip_template argument is used as a customization template for tooltips, also located in the tooltip category. This template allows you to customize the content and format of tooltips in a visualization, using specific variables from the dataframe to display detailed and relevant information when hovering over elements of the visualization.Its hdtype is Txt (text), and the possible values are text that match the names of variables in the dataframe.

